# Generated by Sterling SDK Generator — test suite
# Orchestrator Control Plane API v0.1.0

"""Tests for VersSdkClient — verifies URL construction, HTTP methods, and error handling."""

import asyncio
from typing import Any
from unittest.mock import AsyncMock, patch, MagicMock

import sys
import os

# Add src to path so we can import the generated client
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from vers_sdk.client import VersSdkClient
from vers_sdk.errors import APIError, BadRequestError, NotFoundError, InternalServerError


# ── Helpers ──────────────────────────────────────────────────────────────


class FakeResponse:
    """Minimal httpx.Response stand-in for unit tests."""

    def __init__(self, status_code: int = 200, json_body: Any = None) -> None:
        self.status_code = status_code
        self._json = json_body or {}
        self.headers: dict[str, str] = {"content-type": "application/json"}
        self.text = ""
        self.is_success = 200 <= status_code < 300

    def json(self) -> Any:
        return self._json


captured: dict[str, Any] = {}


def make_client() -> VersSdkClient:
    c = VersSdkClient(base_url="http://localhost:9999", api_key="test-key", max_retries=0)
    return c


def make_mock(status: int = 200, body: Any = None) -> AsyncMock:
    """Return an AsyncMock that records calls and returns a FakeResponse."""

    async def _request(method: str, path: str, **kwargs: Any) -> FakeResponse:
        captured["method"] = method
        captured["path"] = path
        captured["kwargs"] = kwargs
        resp = FakeResponse(status, body)
        if not resp.is_success:
            raise APIError.generate(status=status, body=body, message=None, headers={})
        return resp

    mock = AsyncMock(side_effect=_request)
    return mock


# ── Operation tests ──────────────────────────────────────────────────────


def run(coro: Any) -> Any:
    return asyncio.get_event_loop().run_until_complete(coro)


def test_resize_vm_disk() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.resize_vm_disk("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "PATCH", f"expected PATCH, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_exec_vm_stream_attach() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.exec_vm_stream_attach("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_create_new_root_vm() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.create_new_root_vm({}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_vm_logs() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.vm_logs("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_branch_by_ref() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.branch_by_ref("test-id", "test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_public_commits() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_public_commits())
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_public_repo_tags() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_public_repo_tags("test-id", "test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_branch_by_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.branch_by_tag("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_branch_vm() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.branch_vm("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_get_repo_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.get_repo_tag("test-id", "test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_delete_repo_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.delete_repo_tag("test-id", "test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "DELETE", f"expected DELETE, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_update_repo_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.update_repo_tag("test-id", "test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "PATCH", f"expected PATCH, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_get_repository() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.get_repository("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_delete_repository() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.delete_repository("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "DELETE", f"expected DELETE, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_parent_commits() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_parent_commits("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_update_vm_state() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.update_vm_state("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "PATCH", f"expected PATCH, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_fork_repository() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.fork_repository({}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_repositories() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_repositories())
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_create_repository() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.create_repository({}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_restore_from_commit() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.restore_from_commit({}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_get_domain() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.get_domain("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_delete_domain() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.delete_domain("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "DELETE", f"expected DELETE, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_tags() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_tags())
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_create_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.create_tag({}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_public_repositories() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_public_repositories())
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_get_public_repo_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.get_public_repo_tag("test-id", "test-id", "test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_get_vm_metadata() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.get_vm_metadata("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_env_vars() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_env_vars())
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_set_env_vars() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.set_env_vars({}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "PUT", f"expected PUT, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_delete_vm() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.delete_vm("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "DELETE", f"expected DELETE, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_commits() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_commits())
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_get_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.get_tag("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_delete_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.delete_tag("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "DELETE", f"expected DELETE, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_update_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.update_tag("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "PATCH", f"expected PATCH, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_branch_by_vm() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.branch_by_vm("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_delete_env_var() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.delete_env_var("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "DELETE", f"expected DELETE, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_exec_vm_stream() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.exec_vm_stream("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_commit_vm() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.commit_vm("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_delete_commit() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.delete_commit("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "DELETE", f"expected DELETE, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_update_commit() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.update_commit("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "PATCH", f"expected PATCH, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_repo_tags() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_repo_tags("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_create_repo_tag() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.create_repo_tag("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_ssh_key() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.ssh_key("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_exec_vm() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.exec_vm("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_set_repository_visibility() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.set_repository_visibility("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "PATCH", f"expected PATCH, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_vms() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_vms())
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_list_domains() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.list_domains())
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_create_domain() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.create_domain({}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_vm_status() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.vm_status("test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_get_public_repository() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.get_public_repository("test-id", "test-id"))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "GET", f"expected GET, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"

def test_branch_by_commit() -> None:
    captured.clear()
    c = make_client()
    c._request = make_mock()  # type: ignore[assignment]
    try:
        run(c.branch_by_commit("test-id", {}))
    except Exception:
        pass  # we only care about the captured request
    assert captured.get("method") == "POST", f"expected POST, got {captured.get('method')}"
    assert "path" in captured, "path should be captured"


# ── Error handling tests ─────────────────────────────────────────────────

def test_error_400() -> None:
    c = make_client()
    c._request = make_mock(400, {"message": "bad"})  # type: ignore[assignment]
    try:
        run(c.resize_vm_disk("test-id", {}))
        assert False, "should have raised"
    except BadRequestError:
        pass


def test_error_404() -> None:
    c = make_client()
    c._request = make_mock(404, {"message": "not found"})  # type: ignore[assignment]
    try:
        run(c.resize_vm_disk("test-id", {}))
        assert False, "should have raised"
    except NotFoundError:
        pass


def test_error_500() -> None:
    c = make_client()
    c._request = make_mock(500, {"message": "server"})  # type: ignore[assignment]
    try:
        run(c.resize_vm_disk("test-id", {}))
        assert False, "should have raised"
    except InternalServerError:
        pass


# ── Main runner ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    import inspect

    tests = [(name, obj) for name, obj in globals().items() if name.startswith("test_") and inspect.isfunction(obj)]
    passed = failed = 0
    for name, fn in tests:
        try:
            fn()
            passed += 1
            print(f"  ✓ {name}")
        except Exception as exc:
            failed += 1
            print(f"  ✗ {name}: {exc}")
    print(f"\n{passed} passed, {failed} failed")
    if failed:
        sys.exit(1)
