# Generated by Sterling SDK Generator
# Orchestrator Control Plane API v0.1.0

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional, Union

@dataclass
class EnvVarsResponse:
    """Response body for GET /env_vars and PUT /env_vars."""
    #: All environment variables currently set for the authenticated user.
    vars: dict[str, str]

@dataclass
class CreateRepositoryResponse:
    """Response body for POST /api/v1/repositories"""
    #: The name of the repository
    name: str
    #: The ID of the newly created repository
    repo_id: str

@dataclass
class PublicRepositoryInfo:
    """Public repository information (includes owner org name for namespacing)"""
    #: When the repository was created
    created_at: str
    #: Full reference: org_name/repo_name
    full_name: str
    #: The repository name
    name: str
    #: The owning organization's name (namespace)
    org_name: str
    #: The repository's unique identifier
    repo_id: str
    #: Optional description
    description: Optional[str] = None

@dataclass
class WhoamiOrg:
    """"""
    id: str
    name: str

@dataclass
class ListTagsResponse:
    """Response body for GET /api/v1/commit_tags"""
    #: List of all tags in the user's organization
    tags: list[TagInfo]

@dataclass
class CreateRepoTagRequest:
    """Request body for creating a tag within a repository: POST /api/v1/repositories/{repo_name}/tags"""
    #: The commit ID this tag should point to
    commit_id: str
    #: The tag name (e.g. 'latest', 'v1.0')
    tag_name: str
    #: Optional description of what this tag represents
    description: Optional[str] = None

@dataclass
class OrchestratorVersion:
    """Response struct for GET api/v1/system/version"""
    #: Executable identifier; should be 'orchestrator'
    executable_name: str
    #: Current git hash used for the build
    git_hash: str
    #: Current workspace version
    workspace_version: str

@dataclass
class WhoamiApiKey:
    """"""
    created_at: str
    id: str
    label: str
    expires_at: Optional[str] = None
    max_memory_mib: Optional[int] = None
    max_vcpus: Optional[int] = None

@dataclass
class CommitVmRequest:
    """Request body for POST /vm/{vm_id}/commit"""
    #: Optional description for the commit.
    description: Optional[str] = None
    #: Optional human-readable name for the commit. Defaults to auto-generated name if not provided.
    name: Optional[str] = None

@dataclass
class ListCommitsResponse:
    """"""
    commits: list[CommitInfo]
    limit: int
    offset: int
    total: int

@dataclass
class DeployResponse:
    """Response body for `POST /api/v1/deploy`."""
    project_id: str
    status: str
    vm_id: str

@dataclass
class ListRepoTagsResponse:
    """Response body for GET /api/v1/repositories/{repo_name}/tags"""
    #: The repository name
    repository: str
    #: List of tags in this repository
    tags: list[RepoTagInfo]

@dataclass
class BaseImageInfo:
    """"""
    base_image_id: str
    created_at: str
    image_name: str
    is_public: bool
    owner_id: str
    size_mib: int
    source_type: str
    description: Optional[str] = None

@dataclass
class VmExecResponse:
    """Response body for POST /api/vm/{vm_id}/exec"""
    #: Exit code returned by the command.
    exit_code: int
    #: UTF-8 decoded stderr (lossy).
    stderr: str
    #: UTF-8 decoded stdout (lossy).
    stdout: str
    #: Exec identifier associated with this run.
    exec_id: Optional[str] = None

@dataclass
class CreateBaseImageResponse:
    """"""
    image_name: str
    job_id: str
    status: str

@dataclass
class VmExecRequest:
    """Request body for POST /api/vm/{vm_id}/exec"""
    #: Command and arguments to execute.
    command: list[str]
    #: Optional environment variables to set for the process.
    env: Optional[dict[str, str]] = None
    #: Optional exec identifier for tracking.
    exec_id: Optional[str] = None
    #: Optional stdin payload passed to the command.
    stdin: Optional[str] = None
    #: Timeout in seconds (0 = no timeout).
    timeout_secs: Optional[int] = None
    #: Optional working directory for the command.
    working_dir: Optional[str] = None

@dataclass
class NewVmsResponse:
    """"""
    vms: list[NewVmResponse]

@dataclass
class VmExecStreamAttachRequest:
    """Request body for POST /api/vm/{vm_id}/exec/stream/attach"""
    #: Identifier of the exec stream session to reattach to.
    exec_id: str
    #: Optional cursor to resume from (exclusive). If omitted, the full retained backlog is replayed.
    cursor: Optional[int] = None
    #: Start streaming after the latest retained chunk (ignores cursor).
    from_latest: Optional[bool] = None

@dataclass
class VmUpdateStateRequest:
    """Request body for PATCH /api/vm/{vm_id}/state"""
    #: The requested state for the VM
    state: VmUpdateStateEnum

@dataclass
class DeleteBaseImageResponse:
    """"""
    base_image_id: str
    deleted: bool

@dataclass
class ListPublicRepositoriesResponse:
    """Response body for GET /api/v1/public/repositories"""
    repositories: list[PublicRepositoryInfo]

@dataclass
class CreateTagRequest:
    """Request body for POST /api/v1/commit_tags"""
    #: The commit ID this tag should point to
    commit_id: str
    #: The name of the tag (alphanumeric, hyphens, underscores, dots, 1-64 chars)
    tag_name: str
    #: Optional description of what this tag represents
    description: Optional[str] = None

@dataclass
class ListRepositoriesResponse:
    """Response body for GET /api/v1/repositories"""
    #: List of all repositories in the user's organization
    repositories: list[RepositoryInfo]

@dataclass
class CreateRepoTagResponse:
    """Response body for POST /api/v1/repositories/{repo_name}/tags"""
    #: The commit ID this tag points to
    commit_id: str
    #: Full reference in image_name:tag format
    reference: str
    #: The ID of the newly created tag
    tag_id: str

@dataclass
class CommitInfo:
    """"""
    commit_id: str
    created_at: str
    is_public: bool
    name: str
    owner_id: str
    description: Optional[str] = None
    grandparent_commit_id: Optional[str] = None
    parent_vm_id: Optional[str] = None

@dataclass
class DeleteDomainResponse:
    """Response body for DELETE /api/v1/domains/{domain_id}"""
    domain_id: str

@dataclass
class RepositoryInfo:
    """Repository information returned in list and get operations"""
    #: When the repository was created
    created_at: str
    #: Whether this repository is publicly visible
    is_public: bool
    #: The repository name
    name: str
    #: The repository's unique identifier
    repo_id: str
    #: Optional description
    description: Optional[str] = None

@dataclass
class ValidateKeyResponse:
    """Response body for POST /api/keys/validate"""
    message: str
    valid: bool

@dataclass
class VmSshKeyResponse:
    """Response body for GET /api/vm/{vm_id}/ssh_key"""
    #: The SSH port that will be DNAT'd to the VM's netns (and, in turn, to its TAP device)
    ssh_port: int
    #: Private SSH key in stringified OpenSSH format
    ssh_private_key: str

class VmState(str, Enum):
    """The state of a VM"""
    BOOTING = "booting"
    RUNNING = "running"
    PAUSED = "paused"
    SLEEPING = "sleeping"
    DEAD = "dead"

@dataclass
class VmReadFileResponse:
    """Response body for GET /api/vm/{vm_id}/files"""
    #: File contents, base64-encoded.
    content_b64: str

@dataclass
class SetEnvVarsRequest:
    """Request body for PUT /env_vars — sets (upserts) one or more environment variables.  # Lifecycle model  Environment variables are written to `/etc/environment` inside a VM **once at boot time** via a vsock `WriteFile` request. They are **not** live-synced to running VMs. This is intentional: VMs are ephemeral (create → use → destroy/branch), so env var changes naturally take effect on the next VM.  The `replace` flag exists so callers can atomically express 'I want exactly these variables and nothing else' without having to DELETE each stale key individually. Without it, the only way to remove a variable from future VMs is a separate `DELETE /env_vars/{key}` call per key."""
    #: Key-value pairs to set. Keys must be valid shell identifiers (`^[A-Za-z_][A-Za-z0-9_]*$`, max 256 chars). Values max 8192 chars.  When `replace` is false (default): existing keys are overwritten, keys not mentioned are left untouched (upsert semantics).  When `replace` is true: all existing variables are deleted first, then only the provided vars are stored (replace-all semantics).
    vars: dict[str, str]
    #: If true, delete all existing variables before writing the new set. This gives 'set exactly these vars' semantics. Default: false (upsert).
    replace: Optional[bool] = None

@dataclass
class VmCommitResponse:
    """The response body for POST /api/vm/{vm_id}/commit"""
    #: The UUID of the newly-created commit
    commit_id: str

@dataclass
class ForkRepositoryResponse:
    """Response body for POST /api/v1/repositories/fork"""
    #: The new commit in your org (snapshot of the forked VM)
    commit_id: str
    #: Full reference: repo_name:tag_name
    reference: str
    #: The new repository name in your org
    repo_name: str
    #: The tag name pointing to the forked commit
    tag_name: str
    #: The new VM that was created from the fork
    vm_id: str

@dataclass
class ImageSourceRequestImageRefVariant:
    """"""
    image_ref: str
    type: str

@dataclass
class ImageSourceRequestBucketVariant:
    """"""
    bucket: str
    key: str
    type: str

ImageSourceRequest = Union[ImageSourceRequestImageRefVariant, ImageSourceRequestBucketVariant]

class VmUpdateStateEnum(str, Enum):
    """Possible options for the state requested in PATCH /api/vm/{vm_id}/state"""
    SLEEPING = "Sleeping"
    RUNNING = "Running"

@dataclass
class ErrorResponse:
    """"""
    #: Reason of error
    error: Optional[str] = None
    #: Is always: false
    success: Optional[bool] = None

@dataclass
class UpdateCommitRequest:
    """Request body for PATCH /commits/{commit_id}"""
    is_public: bool
    #: Optional description for the commit.
    description: Optional[str] = None
    #: Optional human-readable name for the commit.
    name: Optional[str] = None

@dataclass
class CreateRepositoryRequest:
    """Request body for POST /api/v1/repositories"""
    #: The name of the repository (alphanumeric, hyphens, underscores, dots, 1-64 chars)
    name: str
    #: Optional description of the repository
    description: Optional[str] = None

@dataclass
class DomainResponse:
    """Response type for domain operations."""
    created_at: str
    domain: str
    domain_id: str
    vm_id: str

@dataclass
class DeploySettings:
    """Settings for the deploy build pipeline."""
    build_command: Optional[str] = None
    install_command: Optional[str] = None
    run_command: Optional[str] = None
    working_directory: Optional[str] = None

@dataclass
class CreateBaseImageRequest:
    """"""
    image_name: str
    source: ImageSourceRequest
    description: Optional[str] = None
    #: Additional capacity in MiB beyond the actual filesystem size (defaults to 256). The final image size = calculated rootfs size + this value. Set to 0 for minimum possible image size, or higher for more free space.
    size_mib: Optional[int] = None

@dataclass
class ForkRepositoryRequest:
    """Request body for POST /api/v1/repositories/fork"""
    #: The organization that owns the source public repository
    source_org: str
    #: The source repository name
    source_repo: str
    #: The tag to fork (e.g. 'latest', 'v1.0')
    source_tag: str
    #: Name for the new repository in your org (defaults to source_repo if omitted)
    repo_name: Optional[str] = None
    #: Tag name in the new repo (defaults to source_tag if omitted)
    tag_name: Optional[str] = None

@dataclass
class VmCommitEntity:
    """"""
    created_at: str
    id: str
    #: Whether this commit is publicly accessible (readable/restorable by anyone).
    is_public: bool
    name: str
    #: api key id.
    owner_id: str
    description: Optional[str] = None
    #: The commit that this commit's parent VM was started from, if any. Intended to optimize traversing the commit tree.
    grandparent_commit_id: Optional[str] = None
    #: The VM that this commit was created from, if any.
    parent_vm_id: Optional[str] = None

@dataclass
class TagInfo:
    """Tag information returned in list and get operations"""
    #: The commit ID this tag currently points to
    commit_id: str
    #: When the tag was created
    created_at: str
    #: The tag's unique identifier
    tag_id: str
    #: The name of the tag
    tag_name: str
    #: When the tag was last updated (moved to different commit or description changed)
    updated_at: str
    #: Optional description of what this tag represents
    description: Optional[str] = None

@dataclass
class VmWriteFileRequest:
    """Request body for PUT /api/vm/{vm_id}/files"""
    #: File contents, base64-encoded.
    content_b64: Optional[str] = None
    #: Create parent directories if they don't exist.
    create_dirs: Optional[bool] = None
    #: File mode (e.g. 0644). Defaults to 0644 if omitted.
    mode: Optional[int] = None
    #: Destination path on the VM.
    path: Optional[str] = None

class VmExecLogStream(str, Enum):
    """Streams available for exec logging."""
    STDOUT = "stdout"
    STDERR = "stderr"

@dataclass
class VmExecLogEntry:
    """Individual log entry describing emitted stdout/stderr chunk."""
    #: Base64-encoded bytes from stdout/stderr chunk.
    data_b64: str
    stream: VmExecLogStream
    timestamp: str
    exec_id: Optional[str] = None

@dataclass
class LabelVmRequest:
    """Request body for `PATCH /vm/{vm_id}/label` (upsert) and `PUT /vm/{vm_id}/labels` (replace).  `labels` is **required** on both endpoints. Sending a body without the field deserializes to a 400 — this is deliberate: the previous `Option<HashMap<…>>` shape silently no-op'd PATCH and (worse) silently wiped every label on PUT. An empty map (`{ 'labels': {} }`) is still accepted as an explicit 'clear all' for PUT and an explicit 'no-op' for PATCH."""
    labels: dict[str, str]

@dataclass
class VmMetadataResponse:
    """Response for GET /api/v1/vm/{vm_id}/metadata"""
    created_at: str
    ip: str
    #: RAM in MiB allocated to this VM at create-time.
    mem_size_mib: int
    owner_id: str
    state: VmState
    #: vCPUs allocated to this VM at create-time.
    vcpu_count: int
    vm_id: str
    deleted_at: Optional[str] = None
    grandparent_vm_id: Optional[str] = None
    parent_commit_id: Optional[str] = None

@dataclass
class WhoamiResponse:
    """Response body for `GET /api/v1/whoami`.  Identifies the principal (user + organization) behind the bearer token used for the request, plus minimal metadata about the API key itself.  The endpoint is read-only and requires only a valid API key — useful for answering questions like 'whose account does this key belong to?' without needing direct database access. Modeled after GitHub's `GET /user`."""
    api_key: WhoamiApiKey
    org: WhoamiOrg
    user: WhoamiUser

@dataclass
class SetRepositoryVisibilityRequest:
    """Request body for PATCH /api/v1/repositories/{repo_name}/visibility"""
    #: Whether the repository should be publicly visible
    is_public: bool

@dataclass
class UpdateRepoTagRequest:
    """Request body for PATCH /api/v1/repositories/{repo_name}/tags/{tag_name}"""
    #: Optional new commit ID to move the tag to
    commit_id: Optional[str] = None
    #: Optional new description for the tag. Send `null` to clear.
    description: Optional[str] = None

@dataclass
class VmCreateVmConfig:
    """Struct representing configuration options common to all VMs"""
    #: The disk size, in MiB.
    fs_size_mib: Optional[int] = None
    #: The filesystem base image name. Currently, must be 'default'
    image_name: Optional[str] = None
    #: The kernel name. Currently, must be 'default.bin'
    kernel_name: Optional[str] = None
    labels: Optional[dict[str, str]] = None
    #: The RAM size, in MiB.
    mem_size_mib: Optional[int] = None
    #: How many vCPUs to allocate to this VM (and its children)
    vcpu_count: Optional[int] = None

@dataclass
class NewVmResponse:
    """Response body for new VM requests (new_root, from_commit, branch)"""
    vm_id: str

@dataclass
class FromCommitVmRequestCommitIdVariant:
    """Request body for POST /api/v1/vm/from_commit"""
    commit_id: str

@dataclass
class FromCommitVmRequestTagNameVariant:
    """Request body for POST /api/v1/vm/from_commit"""
    tag_name: str

@dataclass
class FromCommitVmRequestRefVariant:
    """Request body for POST /api/v1/vm/from_commit"""
    ref: str

FromCommitVmRequest = Union[FromCommitVmRequestCommitIdVariant, FromCommitVmRequestTagNameVariant, FromCommitVmRequestRefVariant]

@dataclass
class VM:
    """"""
    created_at: str
    owner_id: str
    state: VmState
    vm_id: str
    labels: Optional[dict[str, str]] = None

@dataclass
class CreateDomainRequest:
    """Request body for POST /api/v1/domains"""
    domain: str
    vm_id: str

@dataclass
class UpdateTagRequest:
    """Request body for PATCH /api/v1/commit_tags/{tag_name}  For `description`: - Field absent from JSON → don't change the description - Field present as `null` → clear the description - Field present as `'text'` → set the description to 'text'"""
    #: Optional new commit ID to move the tag to
    commit_id: Optional[str] = None
    #: Optional new description for the tag. Send `null` to clear an existing description.
    description: Optional[str] = None

@dataclass
class UploadBaseImageResponse:
    """"""
    image_name: str
    job_id: str
    status: str

@dataclass
class WhoamiUser:
    """"""
    email: str
    id: str
    user_name: str

@dataclass
class BaseImageStatusResponse:
    """"""
    image_name: str
    size_mib: int
    status: str
    error_message: Optional[str] = None

@dataclass
class ListBaseImagesResponse:
    """"""
    images: list[BaseImageInfo]
    limit: int
    offset: int
    total: int

@dataclass
class NewRootRequest:
    """"""
    vm_config: VmCreateVmConfig

@dataclass
class VmResizeDiskRequest:
    """Request body for PATCH /api/vm/{vm_id}/disk"""
    #: The new disk size in MiB. Must be strictly greater than the current size.
    fs_size_mib: int

@dataclass
class VmDeleteResponse:
    """Response body for DELETE /api/vm/{vm_id}"""
    vm_id: str

@dataclass
class CreateTagResponse:
    """Response body for POST /api/v1/commit_tags"""
    #: The commit ID this tag points to
    commit_id: str
    #: The ID of the newly created tag
    tag_id: str
    #: The name of the tag
    tag_name: str

@dataclass
class DeployRequest:
    """Request body for `POST /api/v1/deploy`."""
    #: GitHub repository in `owner/repo` format.
    repo: str
    #: Git branch to clone (defaults to repo default branch).
    branch: Optional[str] = None
    #: Optional project name (defaults to repo name).
    name: Optional[str] = None
    settings: Optional[Any] = None

@dataclass
class RepoTagInfo:
    """Tag information within a repository context"""
    #: The commit ID this tag currently points to
    commit_id: str
    #: When the tag was created
    created_at: str
    #: Full reference in image_name:tag format
    reference: str
    #: The tag's unique identifier
    tag_id: str
    #: The tag name
    tag_name: str
    #: When the tag was last updated
    updated_at: str
    #: Optional description
    description: Optional[str] = None

@dataclass
class VmExecLogResponse:
    """Response for exec log tail requests."""
    #: Returned log entries.
    entries: list[VmExecLogEntry]
    #: True when the end of file was reached.
    eof: bool
    #: Next byte offset to continue from.
    next_offset: int


# ── Params types for operations with query parameters ───────────────

@dataclass
class VmLogsParams:
    """Byte offset into the log file (default: 0)"""
    offset: Optional[int] = None
    """Maximum number of log entries to return"""
    max_entries: Optional[int] = None
    """Filter by 'stdout' or 'stderr'"""
    stream: Optional[str] = None

@dataclass
class UpdateVmStateParams:
    """If true, error immediately if the VM is not finished booting. Defaults to false"""
    skip_wait_boot: Optional[bool] = None

@dataclass
class ReadFileVmParams:
    """Absolute path of the file to read"""
    path: Optional[str] = None

@dataclass
class ResizeVmDiskParams:
    """If true, return an error immediately if the VM is still booting. Default: false"""
    skip_wait_boot: Optional[bool] = None

@dataclass
class CreateNewRootVmParams:
    """If true, wait for the newly-created VM to finish booting before returning. Default: false."""
    wait_boot: Optional[bool] = None

@dataclass
class BranchByRefParams:
    """Number of VMs to branch (optional; default 1)"""
    count: Optional[int] = None

@dataclass
class BranchByTagParams:
    """Number of VMs to branch (optional; default 1)"""
    count: Optional[int] = None

@dataclass
class BranchVmParams:
    """If true, keep VM paused after commit. Only applicable when branching a VM ID."""
    keep_paused: Optional[bool] = None
    """If true, immediately return an error if VM is booting instead of waiting. Only applicable when branching a VM ID."""
    skip_wait_boot: Optional[bool] = None
    """Number of VMs to branch (optional; default 1)"""
    count: Optional[int] = None

@dataclass
class DeleteVmParams:
    """If true, return an error immediately if the VM is still booting. Default: false"""
    skip_wait_boot: Optional[bool] = None

@dataclass
class BranchByVmParams:
    """If true, keep VM paused after commit"""
    keep_paused: Optional[bool] = None
    """If true, immediately return an error if VM is booting instead of waiting"""
    skip_wait_boot: Optional[bool] = None
    """Number of VMs to branch (optional; default 1)"""
    count: Optional[int] = None

@dataclass
class CommitVmParams:
    """If true, keep VM paused after commit"""
    keep_paused: Optional[bool] = None
    """If true, return an error immediately if the VM is still booting. Default: false"""
    skip_wait_boot: Optional[bool] = None

@dataclass
class ListDomainsParams:
    """Filter by VM ID"""
    vm_id: Optional[str] = None

@dataclass
class BranchByCommitParams:
    """Number of VMs to branch (optional; default 1)"""
    count: Optional[int] = None

